spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hh-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
hh:
  api:
    base-url: https://api.hh.ru

logging:
  level:
    root: INFO                   # по умолчанию
    org.apache.kafka: WARN       # выключить все подробные логи Kafka
    org.springframework.kafka: INFO
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.common.metrics.Metrics: WARN